root: true

parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 6
  project: "./tsconfig.json"
  ecmaFeatures:
    jsx: true
    tsx: true

env:
  browser: true
  es6: true
  mocha: true
  node: true

plugins:
  - react
  - "@typescript-eslint"

extends:
  - plugin:react-hooks/recommended
  - plugin:@typescript-eslint/recommended

globals:
  appConfig: false
  google: false

settings:
  react:
    version: "16.x"

rules:
  # --------------------------------------------------------------------------------------------------------------------
  # Possible errors
  # --------------------------------------------------------------------------------------------------------------------
  no-dupe-keys: error
  no-duplicate-case: error
  no-empty: error
  no-unexpected-multiline: error
  no-unreachable: error
  valid-typeof: error

  # --------------------------------------------------------------------------------------------------------------------
  # Best Practices
  # --------------------------------------------------------------------------------------------------------------------
  block-scoped-var: error
  curly:
    - error
    - all
  dot-location:
    - error
    - property
  eqeqeq:
    - error
    - always
    - null: ignore
  no-else-return: warn
  no-eval: error
  no-multi-spaces: error
  yoda: error

  # --------------------------------------------------------------------------------------------------------------------
  # Variables
  # --------------------------------------------------------------------------------------------------------------------
  no-undef: error
  no-unused-vars: error

  # --------------------------------------------------------------------------------------------------------------------
  # Stylistic issues
  # --------------------------------------------------------------------------------------------------------------------
  array-bracket-spacing:
    - error
    - always
    - objectsInArrays: false
      arraysInArrays: false
  block-spacing: error
  brace-style: error
  comma-spacing: error
  comma-style: error
  computed-property-spacing:
    - error
    - always
  func-call-spacing: error
  indent:
    - error
    - 4
    - SwitchCase: 1
  jsx-quotes:
    - error
    - prefer-double
  key-spacing:
    - error
    - multiLine:
        beforeColon: false
        afterColon: true
        mode: minimum
      singleLine:
        beforeColon: false
        afterColon: true
        mode: strict
  keyword-spacing: error
  max-params:
    - error
    - max: 6
  max-statements-per-line: error
  no-multiple-empty-lines: error
  no-trailing-spaces: error
  no-whitespace-before-property: error
  padded-blocks:
    - error
    - classes: always
  quotes:
    - error
    - double
    - allowTemplateLiterals: true
  semi: error
  space-before-blocks: error
  space-before-function-paren: error
  space-infix-ops: error
  space-unary-ops:
    - error
    - words: true
      nonwords: false

  # --------------------------------------------------------------------------------------------------------------------
  # ES6
  # --------------------------------------------------------------------------------------------------------------------
  arrow-parens:
    - error
    - as-needed
  arrow-spacing: error
  constructor-super: error
  no-const-assign: error
  no-new-symbol: error
  no-this-before-super: error
  no-var: error
  prefer-const: warn

  # --------------------------------------------------------------------------------------------------------------------
  # Plugin React
  # --------------------------------------------------------------------------------------------------------------------
  react/prefer-es6-class: error
  react/jsx-uses-vars: error

  # --------------------------------------------------------------------------------------------------------------------
  # Typescript
  # --------------------------------------------------------------------------------------------------------------------
  "@typescript-eslint/no-explicit-any": off